---
- name: Create consul directory
  file:
    path: "{{ CONSUL_DIR }}"
    state: directory
    mode: 0755

- name: Generate consul encrypt
  shell: dd if=/dev/urandom bs=16 count=1 | base64
  register: CONSUL_ENCRYPT

- name: Parse consul encrypt
  set_fact:
    CONSUL_ENCRYPT="{{ CONSUL_ENCRYPT.stdout }}"

- name: Create consul configuration file
  template:
    src: consul.j2
    dest: "{{ CONSUL_DIR }}/{{ CONSUL_CONF_FILENAME }}"

- name: Start consul docker container
  shell: docker stop consul || true && docker rm consul || true && docker run -d --net=host --name=consul -p 8500:8500 \
       -v /etc/consul.d:/consul/config -v /etc/consul.d/tls:/etc/consul.d/tls --restart unless-stopped consul agent \
       -ui -bind=127.0.0.1 -http-port="{{ CONSUL_PORT }}"
